spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shixun?serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10GB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

server:
   port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描所有MyBatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出MyBatis日志

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




